name: buf-validate

on:
  push:
    paths:
      - "contracts/**"
      - "buf.yaml"
  pull_request:
    paths:
      - "contracts/**"
      - "buf.yaml"

permissions:
  contents: read

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: Setup buf
        uses: bufbuild/buf-setup-action@35c243d7f2a909b1d4e40399b348a7fdab27d78d  # v1.31.0
        with:
          version: 1.31.0

      - name: buf lint
        run: buf lint

      - name: buf breaking (compare to main)
        run: buf breaking --against ".git#branch=main"
